language: node_js
node_js:
  - "stable"
#cache: npm
#cache:
#  bundler: true
#  directories:
#  - node_modules
#  - $HOME/.npm
script:
#  - npm ci
#  - npm install
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  keep_history: true
  on:
    branch: master