language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm install
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 0823ce40eff057d1e996ece078236444b69e0577
  local_dir: build
  keep_history: true
  on:
    branch: master

