language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm install
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 3a9a298b81f39a31e30d5f1db75b9bae657621d5
  local_dir: build
  keep_history: true
  on:
    branch: master

